### ISSUE TITLE
the site sometimes has error cant find the profile (for fans adding)

### ISSUE THREAD

**Issue by barbs88** [kangoka/tiktok-autoviewsv2-py#4]
the site sometimes has error cant find the profile (for fans adding)

the console report errors and stuck on that, it did not resubmit or recheck again

**Comment by kangoka** [comment]
Okay, I'll be looking for it

**Comment by barbs88** [comment]
thank you, i hope you also add this site, for hearts, views, comment hearts and sometimes fans
https://vipto.de/

**Comment by kangoka** [comment]
@barbs88 Hi, can you explain more detailed the error? If you can provide an illustration (screenshot or something), that would be nice.

**Comment by kangoka** [comment]
@barbs88 Are you getting error like this? https://i.imgur.com/WQmJrnD.png

**Comment by barbs88** [comment]
just like that but the info is "Profile not found"

i think this is an error on the website itself, just want to know if you can make the automation, retry the submission of URL of Tiktok when this error appears.

also, I'm trying to edit the code but on this site vipto.de , this one has working hearts option, but I cant make it, I'm new, hope you can make another automation for this site too, thanks so much

**Comment by kangoka** [comment]
Is your profile private? If not private, then I believe this error from the website. Also, I have added error handling so if  error occurs, the program doesn't crash.

For vipto.de, I need to access from RDP, maybe I will make for it

**Comment by barbs88** [comment]
no, my profile is not private, been using homedecorationone site for months, I think that's a site bug when I tried again after few minutes, the error is gone

**Comment by kangoka** [comment]
Okay then, with error handling, now all should be good. And I think, I will make vipto.de ver.

**Comment by barbs88** [comment]
thank you, 

i tried the new one, I think the delay before submitting the request is too long? the new update from homedecoration is 5mins per request

**Comment by kangoka** [comment]
Ah, thank you for your information.

**Comment by barbs88** [comment]
is there a something to bypass this, I am already using VPN but still got this

Try again later
Your computer or network may be sending automated queries. To protect our users, we can't process your request right now. For more details visit our help page

**Comment by barbs88** [comment]
i adjusted the loop delay to 300, i edit the file with IDLE

**Comment by kangoka** [comment]
You can change the delay as you wish, depends on the website's delay. I will close the issues.
